const fs = require('fs');
const path = require('path');

// Load .env.local manually (same pattern as seed.js)
const envPath = path.resolve(__dirname, '..', '.env.local');
if (fs.existsSync(envPath)) {
  const env = fs.readFileSync(envPath, 'utf8');
  env.split(/\r?\n/).forEach((line) => {
    const m = line.match(/^\s*([^#][^=\s]*)\s*=\s*(.*)\s*$/);
    if (m) {
      let val = m[2] || '';
      if ((val.startsWith('"') && val.endsWith('"')) || (val.startsWith("'") && val.endsWith("'"))) {
        val = val.slice(1, -1);
      }
      process.env[m[1]] = val;
    }
  });
}

// 100 plans: 10 chapters of 10 levels. Boss levels: 10, 20, ..., 100.
// Generated by the coach agent against the expanded (~135) exercise pool.
// Curve: early skill exposure toward the 3 main goals (muscle-up, handstand
// push-up -> 90-degree push-up, front lever); planche secondary; legs sprinkled.
const PLANS = [
  { level: 1, is_boss: false, name: 'First Steps', description: 'Your journey begins with the fundamentals that build everything else.', exercises: [{ name: 'Incline Push-up', qty: 8 }, { name: 'Squat', qty: 10 }, { name: 'Plank', qty: 20 }, { name: 'Dead Hang', qty: 15 }, { name: 'Glute Bridge', qty: 10 }] },
  { level: 2, is_boss: false, name: 'Finding Your Base', description: 'Build a steady foundation one rep at a time.', exercises: [{ name: 'Kneeling Push-up', qty: 8 }, { name: 'Squat', qty: 12 }, { name: 'Scapular Pull-up', qty: 6 }, { name: 'Plank', qty: 25 }, { name: 'Calf Raise', qty: 15 }] },
  { level: 3, is_boss: false, name: 'Scapular Awareness', description: 'Teach your shoulder blades to do the heavy lifting.', exercises: [{ name: 'Incline Push-up', qty: 10 }, { name: 'Scapular Push-up', qty: 8 }, { name: 'Scapular Pull-up', qty: 8 }, { name: 'Hollow Body Hold', qty: 15 }, { name: 'Lunge', qty: 8 }] },
  { level: 4, is_boss: false, name: 'Core Spark', description: 'Wake up the core that keeps every skill stable.', exercises: [{ name: 'Kneeling Push-up', qty: 10 }, { name: 'Hollow Body Hold', qty: 18 }, { name: 'Side Plank', qty: 15 }, { name: 'Dead Hang', qty: 20 }, { name: 'Glute Bridge', qty: 12 }] },
  { level: 5, is_boss: false, name: 'Pulling Seeds', description: 'Plant the first seeds of your future pull-up.', exercises: [{ name: 'Scapular Pull-up', qty: 10 }, { name: 'Inverted Row', qty: 6 }, { name: 'Incline Push-up', qty: 12 }, { name: 'Plank', qty: 30 }, { name: 'Squat', qty: 14 }] },
  { level: 6, is_boss: false, name: 'Press Beginnings', description: 'Start tilting your push toward the sky.', exercises: [{ name: 'Push-up', qty: 6 }, { name: 'Scapular Push-up', qty: 10 }, { name: 'Inverted Row', qty: 8 }, { name: 'Side Plank', qty: 18 }, { name: 'Reverse Lunge', qty: 8 }] },
  { level: 7, is_boss: false, name: 'Hollow Strength', description: 'A tight hollow body is the secret to every advanced move.', exercises: [{ name: 'Push-up', qty: 8 }, { name: 'Hollow Body Hold', qty: 22 }, { name: 'Negative Pull-up', qty: 4 }, { name: 'Superman Hold', qty: 18 }, { name: 'Calf Raise', qty: 18 }] },
  { level: 8, is_boss: false, name: 'Vertical Hint', description: 'Get your first taste of pressing overhead.', exercises: [{ name: 'Pike Push-up', qty: 5 }, { name: 'Push-up', qty: 10 }, { name: 'Inverted Row', qty: 10 }, { name: 'Plank', qty: 35 }, { name: 'Lunge', qty: 10 }] },
  { level: 9, is_boss: false, name: 'Negative Power', description: 'Control the descent and you control the lift.', exercises: [{ name: 'Negative Pull-up', qty: 6 }, { name: 'Pike Push-up', qty: 6 }, { name: 'Push-up', qty: 12 }, { name: 'Hollow Body Hold', qty: 25 }, { name: 'Glute Bridge', qty: 15 }] },
  { level: 10, is_boss: true, name: 'Foundation Boss', description: 'Prove your base is solid and unlock the road ahead.', exercises: [{ name: 'Push-up', qty: 14 }, { name: 'Negative Pull-up', qty: 7 }, { name: 'Pike Push-up', qty: 7 }, { name: 'Inverted Row', qty: 12 }, { name: 'Hollow Body Hold', qty: 30 }, { name: 'Squat', qty: 18 }, { name: 'Plank', qty: 40 }] },
  { level: 11, is_boss: false, name: 'Row Builder', description: "Horizontal pulling forges the back you'll need up high.", exercises: [{ name: 'Australian Pull-up', qty: 8 }, { name: 'Push-up', qty: 14 }, { name: 'Pike Push-up', qty: 7 }, { name: 'Side Plank', qty: 22 }, { name: 'Bulgarian Split Squat', qty: 8 }] },
  { level: 12, is_boss: false, name: 'Dip Introduction', description: 'Open the door to powerful pressing strength.', exercises: [{ name: 'Tricep Dip (Bench)', qty: 8 }, { name: 'Push-up', qty: 15 }, { name: 'Negative Pull-up', qty: 7 }, { name: 'Hollow Body Hold', qty: 28 }, { name: 'Reverse Lunge', qty: 10 }] },
  { level: 13, is_boss: false, name: 'Hang Tough', description: 'Grip and shoulders that can hang on for the long haul.', exercises: [{ name: 'Dead Hang', qty: 30 }, { name: 'Australian Pull-up', qty: 10 }, { name: 'Pike Push-up', qty: 8 }, { name: 'Diamond Push-up', qty: 6 }, { name: 'Plank', qty: 40 }] },
  { level: 14, is_boss: false, name: 'Wall Friends', description: 'Meet the wall that will teach you to be upside down.', exercises: [{ name: 'Wall Walks', qty: 3 }, { name: 'Pike Push-up', qty: 9 }, { name: 'Australian Pull-up', qty: 11 }, { name: 'Hollow Body Hold', qty: 30 }, { name: 'Cossack Squat', qty: 8 }] },
  { level: 15, is_boss: false, name: 'First Pull-up', description: 'The moment your chin clears the bar for real.', exercises: [{ name: 'Pull-up', qty: 3 }, { name: 'Negative Pull-up', qty: 6 }, { name: 'Push-up', qty: 16 }, { name: 'Pike Push-up', qty: 9 }, { name: 'Side Plank', qty: 25 }] },
  { level: 16, is_boss: false, name: 'Dip Negatives', description: 'Lower with control toward your first full dip.', exercises: [{ name: 'Dip Negative', qty: 6 }, { name: 'Pull-up', qty: 3 }, { name: 'Australian Pull-up', qty: 12 }, { name: 'Wall Walks', qty: 4 }, { name: 'Lunge', qty: 12 }] },
  { level: 17, is_boss: false, name: 'Hanging Core', description: 'Train the core that hangs beneath the bar.', exercises: [{ name: 'Hanging Knee Raise', qty: 8 }, { name: 'Pull-up', qty: 4 }, { name: 'Pike Push-up', qty: 10 }, { name: 'Diamond Push-up', qty: 8 }, { name: 'Plank', qty: 45 }] },
  { level: 18, is_boss: false, name: 'Wall Handstand', description: 'Hold the line against the wall and trust the inversion.', exercises: [{ name: 'Wall Handstand Hold', qty: 15 }, { name: 'Wall Walks', qty: 5 }, { name: 'Pull-up', qty: 4 }, { name: 'Ring Row', qty: 10 }, { name: 'Bulgarian Split Squat', qty: 10 }] },
  { level: 19, is_boss: false, name: 'Parallel Dips', description: 'Press your bodyweight between the bars with pride.', exercises: [{ name: 'Parallel Bar Dip', qty: 5 }, { name: 'Pull-up', qty: 5 }, { name: 'Pike Push-up', qty: 11 }, { name: 'Hanging Knee Raise', qty: 10 }, { name: 'Hollow Body Hold', qty: 32 }] },
  { level: 20, is_boss: true, name: 'Basics Boss', description: 'Bring together pull, dip, and handstand to clear the decade.', exercises: [{ name: 'Pull-up', qty: 6 }, { name: 'Parallel Bar Dip', qty: 7 }, { name: 'Pike Push-up', qty: 12 }, { name: 'Wall Handstand Hold', qty: 20 }, { name: 'Hanging Knee Raise', qty: 12 }, { name: 'Push-up', qty: 20 }, { name: 'Pistol Squat Negative', qty: 5 }] },
  { level: 21, is_boss: false, name: 'Skin the Cat', description: 'Open your shoulders for the lever skills to come.', exercises: [{ name: 'Skin the Cat', qty: 4 }, { name: 'Pull-up', qty: 6 }, { name: 'Parallel Bar Dip', qty: 7 }, { name: 'Wall Handstand Hold', qty: 22 }, { name: 'Cossack Squat', qty: 10 }] },
  { level: 22, is_boss: false, name: 'Tuck Hold', description: 'Find balance and tension in the tuck position.', exercises: [{ name: 'Tuck Hold', qty: 12 }, { name: 'Pull-up', qty: 7 }, { name: 'Pike Push-up', qty: 12 }, { name: 'Ring Row', qty: 12 }, { name: 'Hollow Body Hold', qty: 35 }] },
  { level: 23, is_boss: false, name: 'Planche Lean Intro', description: 'Lean forward and feel the planche calling your name.', exercises: [{ name: 'Pseudo Planche Lean', qty: 15 }, { name: 'Pull-up', qty: 7 }, { name: 'Parallel Bar Dip', qty: 8 }, { name: 'Hanging Leg Raise', qty: 6 }, { name: 'Bulgarian Split Squat', qty: 12 }] },
  { level: 24, is_boss: false, name: 'L-Sit Seeds', description: 'Lift your legs and discover compression strength.', exercises: [{ name: 'L-Sit to Tuck', qty: 6 }, { name: 'Pull-up', qty: 8 }, { name: 'Pike Push-up', qty: 13 }, { name: 'Tuck Hold', qty: 15 }, { name: 'Diamond Push-up', qty: 10 }] },
  { level: 25, is_boss: false, name: 'Ring Work', description: 'Tame the rings and the instability that comes with them.', exercises: [{ name: 'Ring Support Hold', qty: 15 }, { name: 'Ring Row', qty: 14 }, { name: 'Pull-up', qty: 8 }, { name: 'Pseudo Planche Lean', qty: 18 }, { name: 'Pistol Squat Negative', qty: 6 }] },
  { level: 26, is_boss: false, name: 'Wall HSPU Negative', description: 'Lower toward the ground and meet your handstand push-up goal.', exercises: [{ name: 'Wall Handstand Push-up Negative', qty: 4 }, { name: 'Pike Push-up', qty: 14 }, { name: 'Pull-up', qty: 8 }, { name: 'Parallel Bar Dip', qty: 9 }, { name: 'Hollow Body Hold', qty: 38 }] },
  { level: 27, is_boss: false, name: 'Leg Raise Hang', description: 'Full hanging leg raises forge an iron midsection.', exercises: [{ name: 'Hanging Leg Raise', qty: 8 }, { name: 'Pull-up', qty: 9 }, { name: 'Wall Handstand Push-up Negative', qty: 5 }, { name: 'Skin the Cat', qty: 6 }, { name: 'Archer Squat', qty: 8 }] },
  { level: 28, is_boss: false, name: 'Chin-up Power', description: 'Flip your grip and add raw pulling strength.', exercises: [{ name: 'Chin-up', qty: 6 }, { name: 'Pull-up', qty: 9 }, { name: 'Pike Push-up', qty: 15 }, { name: 'Tuck Hold', qty: 18 }, { name: 'Pseudo Planche Lean', qty: 20 }] },
  { level: 29, is_boss: false, name: 'Tuck Front Lever', description: 'Hang horizontal in a tuck and taste the front lever.', exercises: [{ name: 'Tuck Front Lever Hold', qty: 8 }, { name: 'Pull-up', qty: 10 }, { name: 'Parallel Bar Dip', qty: 10 }, { name: 'Wall Handstand Push-up Negative', qty: 6 }, { name: 'Pistol Squat Negative', qty: 8 }] },
  { level: 30, is_boss: true, name: 'First Skills Boss', description: 'Lever, lean, and invert to conquer the third decade.', exercises: [{ name: 'Tuck Front Lever Hold', qty: 10 }, { name: 'Pull-up', qty: 11 }, { name: 'Wall Handstand Push-up Negative', qty: 6 }, { name: 'Parallel Bar Dip', qty: 11 }, { name: 'Pseudo Planche Lean', qty: 22 }, { name: 'Hanging Leg Raise', qty: 10 }, { name: 'Pistol Squat', qty: 4 }] },
  { level: 31, is_boss: false, name: 'Volume Climb', description: 'More reps in the basics make the skills feel light.', exercises: [{ name: 'Pull-up', qty: 11 }, { name: 'Parallel Bar Dip', qty: 12 }, { name: 'Pike Push-up', qty: 16 }, { name: 'Tuck Front Lever Hold', qty: 11 }, { name: 'Cossack Squat', qty: 12 }] },
  { level: 32, is_boss: false, name: 'Frog Balance', description: 'Balance on your hands and prepare for the planche.', exercises: [{ name: 'Frog Stand', qty: 12 }, { name: 'Pseudo Planche Lean', qty: 24 }, { name: 'Pull-up', qty: 12 }, { name: 'Wall Handstand Push-up Negative', qty: 7 }, { name: 'Hanging Leg Raise', qty: 12 }] },
  { level: 33, is_boss: false, name: 'Archer Press', description: 'Shift the load to one arm with archer push-ups.', exercises: [{ name: 'Archer Push-up', qty: 6 }, { name: 'Pull-up', qty: 12 }, { name: 'Tuck Front Lever Hold', qty: 12 }, { name: 'Ring Dip', qty: 6 }, { name: 'Pistol Squat', qty: 5 }] },
  { level: 34, is_boss: false, name: 'Headstand Control', description: 'Find your line in a controlled headstand.', exercises: [{ name: 'Headstand Hold', qty: 20 }, { name: 'Wall Handstand Push-up Negative', qty: 8 }, { name: 'Pull-up', qty: 13 }, { name: 'Frog Stand', qty: 15 }, { name: 'Bulgarian Split Squat', qty: 14 }] },
  { level: 35, is_boss: false, name: 'Muscle-up Drill', description: 'Drill the transition that bridges pull and dip.', exercises: [{ name: 'Ring Muscle-up Transition Drill', qty: 5 }, { name: 'Pull-up', qty: 13 }, { name: 'Parallel Bar Dip', qty: 13 }, { name: 'Tuck Front Lever Hold', qty: 13 }, { name: 'Hollow Body Hold', qty: 40 }] },
  { level: 36, is_boss: false, name: 'Front Lever Row', description: 'Pull horizontally into the lever to build raw lat power.', exercises: [{ name: 'Front Lever Row', qty: 5 }, { name: 'Tuck Front Lever Hold', qty: 14 }, { name: 'Wall Handstand Push-up Negative', qty: 8 }, { name: 'Archer Push-up', qty: 7 }, { name: 'Pistol Squat', qty: 6 }] },
  { level: 37, is_boss: false, name: 'Tuck Planche', description: 'Lift your feet and hold the first true planche.', exercises: [{ name: 'Tuck Planche Hold', qty: 10 }, { name: 'Frog Stand', qty: 18 }, { name: 'Pull-up', qty: 14 }, { name: 'Ring Muscle-up Transition Drill', qty: 6 }, { name: 'Hanging Leg Raise', qty: 14 }] },
  { level: 38, is_boss: false, name: 'Explosive Pull', description: 'Add speed to your pull and rise toward the muscle-up.', exercises: [{ name: 'Explosive Chin-up', qty: 5 }, { name: 'Pull-up', qty: 14 }, { name: 'Ring Dip', qty: 8 }, { name: 'Tuck Planche Hold', qty: 12 }, { name: 'Cossack Squat', qty: 14 }] },
  { level: 39, is_boss: false, name: 'Weighted Strength', description: 'Load the pull-up to break through plateaus.', exercises: [{ name: 'Weighted Pull-up', qty: 5 }, { name: 'Front Lever Row', qty: 6 }, { name: 'Wall Handstand Push-up Negative', qty: 9 }, { name: 'Tuck Planche Hold', qty: 13 }, { name: 'Pistol Squat', qty: 8 }] },
  { level: 40, is_boss: true, name: 'Intermediate Boss', description: 'Transition, lever, and planche unite at the halfway mark.', exercises: [{ name: 'Ring Muscle-up Transition Drill', qty: 8 }, { name: 'Tuck Front Lever Hold', qty: 16 }, { name: 'Tuck Planche Hold', qty: 14 }, { name: 'Wall Handstand Push-up Negative', qty: 10 }, { name: 'Weighted Pull-up', qty: 6 }, { name: 'Parallel Bar Dip', qty: 15 }, { name: 'Pistol Squat', qty: 8 }] },
  { level: 41, is_boss: false, name: 'Straddle Lever', description: 'Open the legs and edge closer to the full front lever.', exercises: [{ name: 'Straddle Front Lever Hold', qty: 6 }, { name: 'Front Lever Row', qty: 7 }, { name: 'Pull-up', qty: 15 }, { name: 'Tuck Planche Hold', qty: 15 }, { name: 'Hanging Leg Raise', qty: 16 }] },
  { level: 42, is_boss: false, name: 'Advanced Tuck Planche', description: 'Extend the tuck and hold more of your bodyweight out.', exercises: [{ name: 'Advanced Tuck Planche', qty: 8 }, { name: 'Pseudo Planche Lean', qty: 28 }, { name: 'Ring Muscle-up Transition Drill', qty: 9 }, { name: 'Weighted Pull-up', qty: 7 }, { name: 'Shrimp Squat', qty: 6 }] },
  { level: 43, is_boss: false, name: 'L-Sit Hold', description: 'Lock out a clean L-sit and own your compression.', exercises: [{ name: 'L-Sit', qty: 12 }, { name: 'Straddle Front Lever Hold', qty: 7 }, { name: 'Ring Dip', qty: 10 }, { name: 'Wall Handstand Push-up Negative', qty: 10 }, { name: 'Pistol Squat', qty: 9 }] },
  { level: 44, is_boss: false, name: 'Archer Pull', description: 'Bias one arm in the pull to chase the one-arm dream.', exercises: [{ name: 'Archer Pull-up', qty: 5 }, { name: 'Pull-up', qty: 16 }, { name: 'Advanced Tuck Planche', qty: 9 }, { name: 'Front Lever Row', qty: 8 }, { name: 'Bulgarian Split Squat', qty: 16 }] },
  { level: 45, is_boss: false, name: 'Ring Dips Deep', description: 'Press deep on the rings for shoulder and tricep armor.', exercises: [{ name: 'Ring Dip', qty: 12 }, { name: 'Ring Muscle-up Transition Drill', qty: 10 }, { name: 'Straddle Front Lever Hold', qty: 8 }, { name: 'Advanced Tuck Planche', qty: 10 }, { name: 'Hanging Leg Raise', qty: 18 }] },
  { level: 46, is_boss: false, name: 'Typewriter Pull', description: 'Slide across the bar and build asymmetric strength.', exercises: [{ name: 'Typewriter Pull-up', qty: 5 }, { name: 'Archer Pull-up', qty: 6 }, { name: 'Wall Handstand Push-up Negative', qty: 11 }, { name: 'L-Sit', qty: 14 }, { name: 'Pistol Squat', qty: 10 }] },
  { level: 47, is_boss: false, name: 'Pistol Power', description: 'Single-leg strength that carries over to everything.', exercises: [{ name: 'Pistol Squat', qty: 12 }, { name: 'Pull-up', qty: 17 }, { name: 'Advanced Tuck Planche', qty: 11 }, { name: 'Straddle Front Lever Hold', qty: 9 }, { name: 'Ring Dip', qty: 13 }] },
  { level: 48, is_boss: false, name: 'Headstand Press', description: 'Begin pressing toward your inverted control.', exercises: [{ name: 'Press to Headstand', qty: 4 }, { name: 'Headstand Hold', qty: 30 }, { name: 'Wall Handstand Push-up Negative', qty: 12 }, { name: 'Front Lever Row', qty: 9 }, { name: 'Shrimp Squat', qty: 8 }] },
  { level: 49, is_boss: false, name: 'Skill Density', description: 'Pack the key skills tighter as the boss approaches.', exercises: [{ name: 'Straddle Front Lever Hold', qty: 10 }, { name: 'Advanced Tuck Planche', qty: 12 }, { name: 'Archer Pull-up', qty: 7 }, { name: 'Ring Muscle-up Transition Drill', qty: 11 }, { name: 'L-Sit', qty: 16 }] },
  { level: 50, is_boss: true, name: 'Halfway Boss', description: 'The midpoint test where every intermediate skill is on the line.', exercises: [{ name: 'Ring Muscle-up Transition Drill', qty: 12 }, { name: 'Straddle Front Lever Hold', qty: 12 }, { name: 'Advanced Tuck Planche', qty: 13 }, { name: 'Wall Handstand Push-up Negative', qty: 13 }, { name: 'Archer Pull-up', qty: 8 }, { name: 'Ring Dip', qty: 15 }, { name: 'Pistol Squat', qty: 12 }] },
  { level: 51, is_boss: false, name: 'Transition Spark', description: 'Sharpen the muscle-up transition while pushing lever and planche volume.', exercises: [{ name: 'Ring Muscle-up Transition Drill', qty: 14 }, { name: 'Straddle Front Lever Hold', qty: 13 }, { name: 'Advanced Tuck Planche', qty: 14 }, { name: 'Wall Handstand Push-up Negative', qty: 14 }, { name: 'Archer Pull-up', qty: 9 }, { name: 'Pistol Squat', qty: 13 }] },
  { level: 52, is_boss: false, name: 'Lever Builder', description: 'Stack front lever time and explosive pulling toward your first muscle-up.', exercises: [{ name: 'Explosive Chin-up', qty: 8 }, { name: 'Straddle Front Lever Hold', qty: 14 }, { name: 'Advanced Tuck Planche', qty: 15 }, { name: 'Wall Handstand Push-up Negative', qty: 15 }, { name: 'Ring Dip', qty: 16 }, { name: 'Full Front Lever Hold', qty: 4 }] },
  { level: 53, is_boss: false, name: 'First Flight', description: 'Earn your first true muscle-up and keep planche progressing.', exercises: [{ name: 'Muscle-up', qty: 1 }, { name: 'Ring Muscle-up Transition Drill', qty: 12 }, { name: 'Straddle Front Lever Hold', qty: 15 }, { name: 'Straddle Planche Hold', qty: 6 }, { name: 'Wall Handstand Push-up Negative', qty: 16 }, { name: 'Shrimp Squat', qty: 10 }] },
  { level: 54, is_boss: false, name: 'Pull and Press', description: 'Repeat the muscle-up and deepen straddle planche control.', exercises: [{ name: 'Muscle-up', qty: 2 }, { name: 'Archer Pull-up', qty: 10 }, { name: 'Straddle Planche Hold', qty: 8 }, { name: 'Full Front Lever Hold', qty: 5 }, { name: 'Wall Handstand Push-up Negative', qty: 17 }, { name: 'Ring Dip', qty: 18 }] },
  { level: 55, is_boss: false, name: 'Inversion Strength', description: 'Land your first handstand push-up alongside growing muscle-ups.', exercises: [{ name: 'Handstand Push-up', qty: 1 }, { name: 'Muscle-up', qty: 2 }, { name: 'Straddle Front Lever Hold', qty: 16 }, { name: 'Straddle Planche Hold', qty: 9 }, { name: 'Typewriter Pull-up', qty: 8 }, { name: 'Pistol Squat', qty: 14 }] },
  { level: 56, is_boss: false, name: 'Overhead Power', description: 'Build handstand push-up reps and front lever endurance.', exercises: [{ name: 'Handstand Push-up', qty: 2 }, { name: 'Muscle-up', qty: 3 }, { name: 'Full Front Lever Hold', qty: 6 }, { name: 'Straddle Planche Hold', qty: 10 }, { name: 'One-Arm Chin-up Assisted', qty: 5 }, { name: 'Ring Dip', qty: 20 }] },
  { level: 57, is_boss: false, name: 'Straight-Arm Strength', description: 'Drive planche and lever holds while pressing overhead.', exercises: [{ name: 'Handstand Push-up', qty: 3 }, { name: 'Straddle Planche Hold', qty: 11 }, { name: 'Straddle Front Lever Hold', qty: 17 }, { name: 'Muscle-up', qty: 3 }, { name: 'Archer Pull-up', qty: 11 }, { name: 'Nordic Curl', qty: 6 }] },
  { level: 58, is_boss: false, name: 'Heavy Inversions', description: 'Add handstand push-up volume and full front lever attempts.', exercises: [{ name: 'Handstand Push-up', qty: 4 }, { name: 'Muscle-up', qty: 4 }, { name: 'Full Front Lever Hold', qty: 7 }, { name: 'Straddle Planche Hold', qty: 12 }, { name: 'One-Arm Chin-up Assisted', qty: 6 }, { name: 'Pistol Squat', qty: 15 }] },
  { level: 59, is_boss: false, name: 'Boss Primer', description: 'Tune all three main goals before the milestone test.', exercises: [{ name: 'Muscle-up', qty: 4 }, { name: 'Handstand Push-up', qty: 5 }, { name: 'Straddle Front Lever Hold', qty: 18 }, { name: 'Straddle Planche Hold', qty: 13 }, { name: 'Archer Pull-up', qty: 12 }, { name: 'Ring Dip', qty: 22 }] },
  { level: 60, is_boss: true, name: 'Advanced Gate Boss', description: 'Prove your first muscle-up, handstand push-up, and lever mastery in one test.', exercises: [{ name: 'Muscle-up', qty: 5 }, { name: 'Handstand Push-up', qty: 5 }, { name: 'Straddle Front Lever Hold', qty: 18 }, { name: 'Straddle Planche Hold', qty: 13 }, { name: 'Archer Pull-up', qty: 12 }, { name: 'Full Front Lever Hold', qty: 8 }, { name: 'Pistol Squat', qty: 16 }] },
  { level: 61, is_boss: false, name: 'Rep Engine', description: 'Grow muscle-up and handstand push-up reps after the gate.', exercises: [{ name: 'Muscle-up', qty: 6 }, { name: 'Handstand Push-up', qty: 6 }, { name: 'Full Front Lever Hold', qty: 9 }, { name: 'Straddle Planche Hold', qty: 14 }, { name: 'Typewriter Pull-up', qty: 9 }, { name: 'Shrimp Squat', qty: 11 }] },
  { level: 62, is_boss: false, name: 'Planche Press', description: 'Introduce straddle planche pushing strength with steady pulls.', exercises: [{ name: 'Straddle Planche Hold', qty: 15 }, { name: 'Muscle-up', qty: 6 }, { name: 'Handstand Push-up', qty: 6 }, { name: 'One-Arm Chin-up Assisted', qty: 7 }, { name: 'Full Front Lever Hold', qty: 10 }, { name: 'Ring Dip', qty: 24 }] },
  { level: 63, is_boss: false, name: 'Free Balance', description: 'Work freestanding handstand balance into the strength mix.', exercises: [{ name: 'Freestanding Handstand Hold', qty: 10 }, { name: 'Handstand Push-up', qty: 7 }, { name: 'Muscle-up', qty: 7 }, { name: 'Straddle Front Lever Hold', qty: 20 }, { name: 'Archer Pull-up', qty: 13 }, { name: 'Cossack Squat', qty: 12 }] },
  { level: 64, is_boss: false, name: 'Lever Surge', description: 'Push full front lever time and muscle-up volume higher.', exercises: [{ name: 'Full Front Lever Hold', qty: 11 }, { name: 'Muscle-up', qty: 7 }, { name: 'Handstand Push-up', qty: 7 }, { name: 'Straddle Planche Hold', qty: 16 }, { name: 'One-Arm Chin-up Assisted', qty: 8 }, { name: 'Pistol Squat', qty: 17 }] },
  { level: 65, is_boss: false, name: 'Press Power', description: 'Add freestanding work and one-arm assisted pulling.', exercises: [{ name: 'Freestanding Handstand Hold', qty: 12 }, { name: 'Handstand Push-up', qty: 8 }, { name: 'Muscle-up', qty: 8 }, { name: 'Straddle Front Lever Hold', qty: 22 }, { name: 'Straddle Planche Hold', qty: 17 }, { name: 'Nordic Curl', qty: 7 }] },
  { level: 66, is_boss: false, name: 'Iron Volume', description: 'High-rep muscle-ups and pressing with long lever holds.', exercises: [{ name: 'Muscle-up', qty: 9 }, { name: 'Handstand Push-up', qty: 9 }, { name: 'Full Front Lever Hold', qty: 12 }, { name: 'Straddle Planche Hold', qty: 18 }, { name: 'Typewriter Pull-up', qty: 10 }, { name: 'Ring Dip', qty: 26 }] },
  { level: 67, is_boss: false, name: 'Single-Arm Path', description: 'Deepen one-arm pulling and planche endurance.', exercises: [{ name: 'One-Arm Chin-up Assisted', qty: 9 }, { name: 'Muscle-up', qty: 9 }, { name: 'Handstand Push-up', qty: 9 }, { name: 'Straddle Planche Hold', qty: 19 }, { name: 'Full Front Lever Hold', qty: 13 }, { name: 'Shrimp Squat', qty: 12 }] },
  { level: 68, is_boss: false, name: 'Balanced Beast', description: 'Tie freestanding balance to all main strength lines.', exercises: [{ name: 'Freestanding Handstand Hold', qty: 14 }, { name: 'Muscle-up', qty: 10 }, { name: 'Handstand Push-up', qty: 10 }, { name: 'Straddle Front Lever Hold', qty: 24 }, { name: 'Straddle Planche Hold', qty: 20 }, { name: 'Pistol Squat', qty: 18 }] },
  { level: 69, is_boss: false, name: 'Boss Primer II', description: 'Sharpen every main goal ahead of the second gate.', exercises: [{ name: 'Muscle-up', qty: 10 }, { name: 'Handstand Push-up', qty: 10 }, { name: 'Full Front Lever Hold', qty: 14 }, { name: 'Straddle Planche Hold', qty: 21 }, { name: 'One-Arm Chin-up Assisted', qty: 10 }, { name: 'Ring Dip', qty: 28 }] },
  { level: 70, is_boss: true, name: 'Strength Gauntlet Boss', description: 'Test growing muscle-up, handstand push-up, lever, and planche capacity.', exercises: [{ name: 'Muscle-up', qty: 11 }, { name: 'Handstand Push-up', qty: 11 }, { name: 'Full Front Lever Hold', qty: 15 }, { name: 'Straddle Planche Hold', qty: 22 }, { name: 'One-Arm Chin-up Assisted', qty: 10 }, { name: 'Freestanding Handstand Hold', qty: 15 }, { name: 'Pistol Squat', qty: 18 }] },
  { level: 71, is_boss: false, name: 'Strict Control', description: 'Begin strict, slow muscle-up work with planche pushing.', exercises: [{ name: 'Muscle-up', qty: 11 }, { name: 'Straddle Planche Push-up', qty: 1 }, { name: 'Handstand Push-up', qty: 11 }, { name: 'Full Front Lever Hold', qty: 16 }, { name: 'One-Arm Chin-up Assisted', qty: 11 }, { name: 'Cossack Squat', qty: 14 }] },
  { level: 72, is_boss: false, name: 'Negative Drive', description: 'Heavy wall HSPU negatives to prepare 90-degree pushing.', exercises: [{ name: 'Wall Handstand Push-up Negative', qty: 18 }, { name: 'Straddle Planche Push-up', qty: 2 }, { name: 'Muscle-up', qty: 12 }, { name: 'Full Front Lever Hold', qty: 17 }, { name: 'Archer Pull-up', qty: 14 }, { name: 'Nordic Curl', qty: 8 }] },
  { level: 73, is_boss: false, name: 'Lever Lock', description: 'Push full front lever endurance and planche reps.', exercises: [{ name: 'Full Front Lever Hold', qty: 18 }, { name: 'Straddle Planche Push-up', qty: 3 }, { name: 'Handstand Push-up', qty: 12 }, { name: 'Muscle-up', qty: 12 }, { name: 'One-Arm Chin-up Assisted', qty: 12 }, { name: 'Pistol Squat', qty: 19 }] },
  { level: 74, is_boss: false, name: 'Toward 90', description: 'Introduce 90-degree push-up reps from heavy negatives.', exercises: [{ name: '90-Degree Push-up', qty: 1 }, { name: 'Wall Handstand Push-up Negative', qty: 20 }, { name: 'Straddle Planche Push-up', qty: 3 }, { name: 'Muscle-up', qty: 13 }, { name: 'Full Front Lever Hold', qty: 19 }, { name: 'Shrimp Squat', qty: 13 }] },
  { level: 75, is_boss: false, name: 'Lever Pull', description: 'Add front lever rows and strict pulling power.', exercises: [{ name: '90-Degree Push-up', qty: 2 }, { name: 'Front Lever Row', qty: 6 }, { name: 'Full Front Lever Hold', qty: 20 }, { name: 'Muscle-up', qty: 13 }, { name: 'Straddle Planche Push-up', qty: 4 }, { name: 'One-Arm Pull-up', qty: 1 }] },
  { level: 76, is_boss: false, name: 'Slow Burn', description: 'Strict slow muscle-ups paired with 90-degree pressing.', exercises: [{ name: 'Muscle-up', qty: 14 }, { name: '90-Degree Push-up', qty: 3 }, { name: 'Straddle Planche Push-up', qty: 4 }, { name: 'Full Front Lever Hold', qty: 21 }, { name: 'One-Arm Pull-up', qty: 1 }, { name: 'Pistol Squat', qty: 20 }] },
  { level: 77, is_boss: false, name: 'Front Lever Form', description: 'Attempt clean front lever holds with planche pushing.', exercises: [{ name: 'Front Lever', qty: 3 }, { name: '90-Degree Push-up', qty: 4 }, { name: 'Muscle-up', qty: 14 }, { name: 'Straddle Planche Push-up', qty: 5 }, { name: 'Front Lever Row', qty: 7 }, { name: 'Cossack Squat', qty: 15 }] },
  { level: 78, is_boss: false, name: 'Press Ladder', description: 'Build 90-degree push-up volume and lever strength.', exercises: [{ name: '90-Degree Push-up', qty: 5 }, { name: 'Full Front Lever Hold', qty: 22 }, { name: 'Muscle-up', qty: 15 }, { name: 'Straddle Planche Push-up', qty: 5 }, { name: 'One-Arm Pull-up', qty: 2 }, { name: 'Nordic Curl', qty: 9 }] },
  { level: 79, is_boss: false, name: 'Boss Primer III', description: 'Polish strict muscle-ups, 90-degree pressing, and levers.', exercises: [{ name: 'Muscle-up', qty: 15 }, { name: '90-Degree Push-up', qty: 6 }, { name: 'Front Lever', qty: 4 }, { name: 'Straddle Planche Push-up', qty: 6 }, { name: 'One-Arm Pull-up', qty: 2 }, { name: 'Pistol Squat', qty: 21 }] },
  { level: 80, is_boss: true, name: 'Elite Forge Boss', description: 'Showcase strict muscle-ups, 90-degree pressing, front lever, and planche pushing.', exercises: [{ name: 'Muscle-up', qty: 16 }, { name: '90-Degree Push-up', qty: 6 }, { name: 'Front Lever', qty: 5 }, { name: 'Straddle Planche Push-up', qty: 6 }, { name: 'One-Arm Pull-up', qty: 2 }, { name: 'Full Front Lever Hold', qty: 23 }, { name: 'Shrimp Squat', qty: 14 }] },
  { level: 81, is_boss: false, name: 'Heavy Mastery', description: 'Drive every elite line upward after the forge.', exercises: [{ name: 'Muscle-up', qty: 16 }, { name: '90-Degree Push-up', qty: 7 }, { name: 'Straddle Planche Push-up', qty: 7 }, { name: 'Front Lever', qty: 5 }, { name: 'One-Arm Pull-up', qty: 3 }, { name: 'Pistol Squat', qty: 22 }] },
  { level: 82, is_boss: false, name: 'Lever Endurance', description: 'Long full front lever holds with strict pressing.', exercises: [{ name: 'Full Front Lever Hold', qty: 24 }, { name: '90-Degree Push-up', qty: 7 }, { name: 'Muscle-up', qty: 17 }, { name: 'Straddle Planche Push-up', qty: 7 }, { name: 'One-Arm Pull-up', qty: 3 }, { name: 'Nordic Curl', qty: 10 }] },
  { level: 83, is_boss: false, name: 'Planche Climb', description: 'Increase straddle planche pushing with elite pulling.', exercises: [{ name: 'Straddle Planche Push-up', qty: 8 }, { name: 'Muscle-up', qty: 17 }, { name: '90-Degree Push-up', qty: 8 }, { name: 'Front Lever', qty: 6 }, { name: 'One-Arm Pull-up', qty: 4 }, { name: 'Cossack Squat', qty: 16 }] },
  { level: 84, is_boss: false, name: 'Strict Stack', description: 'Stack strict muscle-up and 90-degree push-up volume.', exercises: [{ name: 'Muscle-up', qty: 18 }, { name: '90-Degree Push-up', qty: 8 }, { name: 'Full Front Lever Hold', qty: 26 }, { name: 'Straddle Planche Push-up', qty: 8 }, { name: 'One-Arm Pull-up', qty: 4 }, { name: 'Pistol Squat', qty: 23 }] },
  { level: 85, is_boss: false, name: 'Lever Power', description: 'Clean front lever reps blended with pressing strength.', exercises: [{ name: 'Front Lever', qty: 7 }, { name: '90-Degree Push-up', qty: 9 }, { name: 'Muscle-up', qty: 18 }, { name: 'Straddle Planche Push-up', qty: 9 }, { name: 'One-Arm Pull-up', qty: 5 }, { name: 'Shrimp Squat', qty: 15 }] },
  { level: 86, is_boss: false, name: 'Elite Volume', description: 'Raise every elite skill toward peak numbers.', exercises: [{ name: 'Muscle-up', qty: 19 }, { name: '90-Degree Push-up', qty: 9 }, { name: 'Straddle Planche Push-up', qty: 9 }, { name: 'Full Front Lever Hold', qty: 28 }, { name: 'One-Arm Pull-up', qty: 5 }, { name: 'Nordic Curl', qty: 11 }] },
  { level: 87, is_boss: false, name: 'Planche Threshold', description: 'Approach the full planche with elite supporting work.', exercises: [{ name: 'Planche', qty: 1 }, { name: 'Straddle Planche Push-up', qty: 10 }, { name: 'Muscle-up', qty: 19 }, { name: '90-Degree Push-up', qty: 10 }, { name: 'Front Lever', qty: 7 }, { name: 'Pistol Squat', qty: 24 }] },
  { level: 88, is_boss: false, name: 'Single-Arm Power', description: 'Heavy one-arm pulling with elite pressing and levers.', exercises: [{ name: 'One-Arm Pull-up', qty: 6 }, { name: 'Muscle-up', qty: 20 }, { name: '90-Degree Push-up', qty: 10 }, { name: 'Full Front Lever Hold', qty: 30 }, { name: 'Straddle Planche Push-up', qty: 10 }, { name: 'Cossack Squat', qty: 17 }] },
  { level: 89, is_boss: false, name: 'Boss Primer IV', description: 'Final tune of all elite skills before the ninth gate.', exercises: [{ name: 'Muscle-up', qty: 20 }, { name: '90-Degree Push-up', qty: 11 }, { name: 'Front Lever', qty: 8 }, { name: 'Straddle Planche Push-up', qty: 11 }, { name: 'One-Arm Pull-up', qty: 6 }, { name: 'Shrimp Squat', qty: 16 }] },
  { level: 90, is_boss: true, name: 'Mastery Crucible Boss', description: 'Test peak muscle-ups, 90-degree pressing, front lever, and planche pushing.', exercises: [{ name: 'Muscle-up', qty: 21 }, { name: '90-Degree Push-up', qty: 11 }, { name: 'Front Lever', qty: 8 }, { name: 'Straddle Planche Push-up', qty: 11 }, { name: 'One-Arm Pull-up', qty: 7 }, { name: 'Full Front Lever Hold', qty: 30 }, { name: 'Pistol Squat', qty: 25 }] },
  { level: 91, is_boss: false, name: 'Peak Engine', description: 'Drive elite reps higher into the final stretch.', exercises: [{ name: 'Muscle-up', qty: 22 }, { name: '90-Degree Push-up', qty: 12 }, { name: 'Straddle Planche Push-up', qty: 12 }, { name: 'Full Front Lever Hold', qty: 32 }, { name: 'One-Arm Pull-up', qty: 7 }, { name: 'Nordic Curl', qty: 12 }] },
  { level: 92, is_boss: false, name: 'Front Lever Peak', description: 'Long clean front lever work with elite pressing.', exercises: [{ name: 'Front Lever', qty: 9 }, { name: '90-Degree Push-up', qty: 12 }, { name: 'Muscle-up', qty: 22 }, { name: 'Straddle Planche Push-up', qty: 12 }, { name: 'One-Arm Pull-up', qty: 8 }, { name: 'Pistol Squat', qty: 26 }] },
  { level: 93, is_boss: false, name: 'Planche Power', description: 'Build full planche reps alongside straddle pushing.', exercises: [{ name: 'Planche', qty: 2 }, { name: 'Straddle Planche Push-up', qty: 13 }, { name: 'Muscle-up', qty: 23 }, { name: '90-Degree Push-up', qty: 13 }, { name: 'Full Front Lever Hold', qty: 34 }, { name: 'Cossack Squat', qty: 18 }] },
  { level: 94, is_boss: false, name: 'Elite Stack', description: 'Stack peak muscle-up and pressing volume.', exercises: [{ name: 'Muscle-up', qty: 24 }, { name: '90-Degree Push-up', qty: 13 }, { name: 'Front Lever', qty: 10 }, { name: 'Straddle Planche Push-up', qty: 13 }, { name: 'One-Arm Pull-up', qty: 8 }, { name: 'Shrimp Squat', qty: 17 }] },
  { level: 95, is_boss: false, name: 'Iron Threshold', description: 'Heavy elite combination across all main goals.', exercises: [{ name: 'Muscle-up', qty: 24 }, { name: '90-Degree Push-up', qty: 14 }, { name: 'Full Front Lever Hold', qty: 36 }, { name: 'Planche', qty: 2 }, { name: 'One-Arm Pull-up', qty: 9 }, { name: 'Nordic Curl', qty: 13 }] },
  { level: 96, is_boss: false, name: 'Planche Mastery', description: 'Full planche reps with straddle pushing and levers.', exercises: [{ name: 'Planche', qty: 3 }, { name: 'Straddle Planche Push-up', qty: 14 }, { name: 'Muscle-up', qty: 25 }, { name: '90-Degree Push-up', qty: 14 }, { name: 'Front Lever', qty: 10 }, { name: 'Pistol Squat', qty: 27 }] },
  { level: 97, is_boss: false, name: 'Peak Pull', description: 'Maximal one-arm pulling with elite pressing power.', exercises: [{ name: 'One-Arm Pull-up', qty: 10 }, { name: 'Muscle-up', qty: 25 }, { name: '90-Degree Push-up', qty: 15 }, { name: 'Full Front Lever Hold', qty: 38 }, { name: 'Straddle Planche Push-up', qty: 14 }, { name: 'Cossack Squat', qty: 19 }] },
  { level: 98, is_boss: false, name: 'Apex Volume', description: 'Push every elite skill to near-peak numbers.', exercises: [{ name: 'Muscle-up', qty: 26 }, { name: '90-Degree Push-up', qty: 15 }, { name: 'Planche', qty: 3 }, { name: 'Front Lever', qty: 11 }, { name: 'Straddle Planche Push-up', qty: 15 }, { name: 'Shrimp Squat', qty: 18 }] },
  { level: 99, is_boss: false, name: 'Final Primer', description: 'Last sharpening of all three main goals plus planche.', exercises: [{ name: 'Muscle-up', qty: 27 }, { name: '90-Degree Push-up', qty: 16 }, { name: 'Full Front Lever Hold', qty: 40 }, { name: 'Planche', qty: 4 }, { name: 'Straddle Planche Push-up', qty: 15 }, { name: 'Pistol Squat', qty: 28 }] },
  { level: 100, is_boss: true, name: 'Grandmaster Boss', description: 'The ultimate test uniting muscle-up, 90-degree push-up, full front lever, and planche mastery.', exercises: [{ name: 'Muscle-up', qty: 28 }, { name: '90-Degree Push-up', qty: 16 }, { name: 'Full Front Lever Hold', qty: 40 }, { name: 'Straddle Planche Push-up', qty: 16 }, { name: 'Planche', qty: 4 }, { name: 'One-Arm Pull-up', qty: 10 }, { name: 'Pistol Squat', qty: 28 }] },
];

async function run() {
  const { createClient } = require('@supabase/supabase-js');
  const url = process.env.EXPO_PUBLIC_SUPABASE_URL;
  const key = process.env.EXPO_PUBLIC_SUPABASE_ANON_KEY;

  if (!url || !key) {
    console.error('Missing Supabase credentials.');
    process.exit(1);
  }

  const supabase = createClient(url, key);

  // Idempotency check — the wipe (run via MCP/SQL before this) empties map_levels.
  const { data: existing } = await supabase.from('map_levels').select('id').limit(1);
  if (existing && existing.length > 0) {
    console.log('map_levels already seeded — skipping. (Wipe it first to reseed.)');
    return;
  }

  // Build exercise name -> id map
  const { data: exercises, error: exErr } = await supabase.from('exercises').select('id, name');
  if (exErr) { console.error('Failed to fetch exercises:', exErr); process.exit(1); }

  const exerciseMap = {};
  for (const ex of exercises) exerciseMap[ex.name] = ex.id;

  // HARD VALIDATION: every referenced exercise must exist. Abort on any miss.
  const missing = [];
  for (const plan of PLANS) {
    for (const ex of plan.exercises) {
      if (!exerciseMap[ex.name]) missing.push(`L${plan.level}: "${ex.name}"`);
    }
  }
  if (missing.length > 0) {
    console.error('Aborting — these exercise names are not in the database:');
    missing.forEach((m) => console.error('  - ' + m));
    process.exit(1);
  }

  // Validate counts and boss placement.
  if (PLANS.length !== 100) { console.error(`Expected 100 plans, got ${PLANS.length}`); process.exit(1); }
  for (const plan of PLANS) {
    if (plan.exercises.length < 5 || plan.exercises.length > 7) {
      console.error(`L${plan.level} has ${plan.exercises.length} exercises (must be 5-7)`); process.exit(1);
    }
    const shouldBeBoss = plan.level % 10 === 0;
    if (plan.is_boss !== shouldBeBoss) {
      console.error(`L${plan.level} boss flag mismatch (is_boss=${plan.is_boss})`); process.exit(1);
    }
  }

  console.log(`Found ${exercises.length} exercises. Seeding ${PLANS.length} plans...`);

  let inserted = 0;
  for (const plan of PLANS) {
    const { data: planData, error: planErr } = await supabase
      .from('workout_plans')
      .insert({ name: plan.name, description: plan.description })
      .select()
      .single();

    if (planErr) {
      console.error(`Failed to insert plan "${plan.name}":`, planErr);
      process.exit(1);
    }

    const exerciseRows = plan.exercises.map((ex, idx) => ({
      workout_plan_id: planData.id,
      exercise_id: exerciseMap[ex.name],
      order_index: idx + 1,
      quantity: ex.qty,
    }));

    const { error: exInsertErr } = await supabase.from('workout_plan_exercises').insert(exerciseRows);
    if (exInsertErr) {
      console.error(`Failed to insert exercises for plan "${plan.name}":`, exInsertErr);
      process.exit(1);
    }

    const { error: levelErr } = await supabase
      .from('map_levels')
      .insert({ level_number: plan.level, workout_plan_id: planData.id, is_boss: plan.is_boss });

    if (levelErr) {
      console.error(`Failed to insert map_level ${plan.level}:`, levelErr);
      process.exit(1);
    }

    inserted++;
    const marker = plan.is_boss ? ' BOSS' : '';
    console.log(`  + Level ${plan.level}${marker}: ${plan.name}`);
  }

  console.log(`\nDone! Seeded ${inserted} levels.`);
}

run().catch((err) => { console.error(err); process.exit(1); });
